### ISSUE TITLE
Moveset combo hits not working

### ISSUE THREAD

**Issue by HalloweenPandas** [KyonkoYuuki/YaMovesetOrganizer#1]
For some characters the hits don't register, this could be an issue with either the bdm entry not properly copying over or the hitbox entry in the BAC not having the proper values.
This happens with:
- Vegito Blue to Vegito
- Bardock to Vegito

Here's an example: https://gyazo.com/dd122c054a9ef9b14c78de96c6fbf33a

**Comment by KyonkoYuuki** [comment]
so this is outside of the moveset manager's scope, but the issue lies in what the developers did with the CMS entry for Vegito.  There is no BDM entry for him (`STR_50` in XML).  If you use `genser` to decompile `\data\system\char_model_spec.cms`
```
    <Entry id="0x27" name="VTO">
        <!--Vegito-->
        <U_10 value="0x2" />
        <LOAD_CAM_DIST value="0x0" />
        <U_16 value="0xc801" />
        <U_18 value="0xffff" />
        <U_1A value="0x400" />
        <CHARACTER value="VTO" />
        <EAN value="VTO" />
        <FCE_EAN value="VTO" />
        <FCE value="" />
        <CAM_EAN value="VTO" />
        <BAC value="VTO" />
        <BCM value="VTO" />
        <AI value="../CL4/CL4" />
        <STR_50 value="" />
    </Entry>
```

For comparison, this is Vegito Blue's
```
    <Entry id="0x8d" name="VTB">
        <!--SSGSS Vegito-->
        <U_10 value="0x2" />
        <LOAD_CAM_DIST value="0x0" />
        <U_16 value="0xc801" />
        <U_18 value="0xffff" />
        <U_1A value="0x400" />
        <CHARACTER value="VTB" />
        <EAN value="VTB" />
        <FCE_EAN value="../VTO/VTO" />
        <FCE value="" />
        <CAM_EAN value="../VTO/VTO" />
        <BAC value="VTB" />
        <BCM value="VTB" />
        <AI value="../CL4/CL4" />
        <STR_50 value="VTB" />
    </Entry>
```

Changing `STR_50` to `VTO` and then compiling it with genser will allow him to use his own BDM and the hits will start to register.
